name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14.x, 15.x, 16.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run lint
    - name: "npm test [14.x]"
      if: ${{ matrix.node == '14.x' }}
      run: npm test
      env:
        NODE_OPTIONS: "--experimental-wasm-bigint"
    - name: "npm test [15.x/16.x]"
      if: ${{ matrix.node != '14.x' }}
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build
    - name: Deploy
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/demos/
        CLEAN: true
        SINGLE_COMMIT: true
        GIT_CONFIG_NAME: "github-actions[bot]"
        GIT_CONFIG_EMAIL: "github-actions[bot]@users.noreply.github.com"
